@startuml

scale 3

hide fields
hide members

package akka_raft.view as view{
  interface ClientObserver
  class MainScreenView
  class Client
  interface ActorRef  
}

MainScreenView --|> ClientObserver
Client ..o ClientObserver
Client -|> ActorRef
MainScreenView ..o ActorRef
@enduml