@startuml sequenceECS

    participant "Coordinator" as Coordinator
    participant "SystemManager" as SystemManager
    participant "ComponentManager" as ComponentManager
    participant "EntityManager" as EntityManager

    activate Coordinator
    activate SystemManager
    activate ComponentManager
    activate EntityManager


    Coordinator -> ComponentManager : registerComponent(componentType)

    Coordinator -> SystemManager : registerSystem(system)

    note right of Coordinator: signature = Set[componentType]

    ComponentManager -> ComponentManager : checkComponent(componentType)
    alt found
      ComponentManager -->Coordinator : Some(component)
    else not Found
      ComponentManager -->Coordinator : unregisteredComponent
    end

    Coordinator -> EntityManager : createEntity(id)
    EntityManager -->  Coordinator : entity
    Coordinator -> ComponentManager : bindEntityComponent(entity, component)
    ComponentManager -> ComponentManager : checkComponent(componentType)

    alt success 
      Coordinator -> SystemManager : entitySignatureChange(entity, signature)
      SystemManager -> SystemManager : RedistributeEntity
    else fail
      ComponentManager --> Coordinator : unregisteredComponent
    end

    Coordinator -> SystemManager : updateAllSystem()
    ...After some time...
    Coordinator -> SystemManager : entityDestroyed(entity)
    Coordinator -> ComponentManager : entityDestroyed(entity)
    Coordinator -> EntityManager : entityDestroyed(entity)

@enduml