# This is a basic workflow to help you get started with Actions
name: Latek Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_latek:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Set selected color
        run: |
          alias echo='echo -e'

      - name: Setup Git repo
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          pre_compile: "tlmgr update --self --all"
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -logfilewarninglist -Werror"
          post_compile: "latexmk -c"
      - name: Split log
        run: cat main.log | grep -n -E 'LaTeX Error|LaTeX Warning' --group-separator======================== > small.log
        if: failure()

      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          name: Logs
          path: |
            main.log
            small.log
        if: failure()
        
      - name: Print small log
        run: cat small.log > &2
        if: failure()
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: main.pdf
        if: always()
