# This is a basic workflow to help you get started with Actions
name: Latek Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_latek:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Git repo
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        
      #- name: Update latexmk
       #pre_compile: "tlmgr update --self --all"
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          post_compile: "latexmk -c"
          args: "-pdf -file-line-error -halt-on-error -interaction=nonstopmode -logfilewarninglist -Werror"
   
      - name: Upload artifacts1
        run: ls -al
        if: always()
      
      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with:
          path: main.log
        if: always()
        
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: main.pdf
        if: always()

